version: '2'
services:
  memcached:
    image: 'memcached:alpine'
    ports:
      - '11211:11211'
  limn:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - ~/.aws:/home/limn/.aws
    depends_on:
      - memcached
    environment:
      MEMCACHE_HOST: memcached
      HOST: 0.0.0.0
      PORT: 5000
      LOG_LEVEL: debug
    links:
      - 'memcached:memcached'
